import { defineConfig, devices } from "@playwright/test";
try {
  process.loadEnvFile?.(".env.local");
} catch {
  /* CI may provide environment variables directly. */
}
const supabaseHostname = (() => {
  try {
    return new URL(process.env.NEXT_PUBLIC_SUPABASE_URL ?? "").hostname;
  } catch {
    return "";
  }
})();
const usesLocalSupabase =
  supabaseHostname === "localhost" ||
  supabaseHostname === "127.0.0.1" ||
  supabaseHostname === "::1";
if (usesLocalSupabase) {
  try {
    process.loadEnvFile?.(".tmp/e2e.local.env");
  } catch {
    /* Optional disposable credentials generated by e2e:user:local. */
  }
}
const e2ePort = process.env.PLAYWRIGHT_PORT ?? "3100";
const e2eBaseUrl =
  process.env.PLAYWRIGHT_BASE_URL ?? `http://127.0.0.1:${e2ePort}`;
export default defineConfig({
  testDir: "./tests/e2e",
  fullyParallel: false,
  workers: process.env.CI ? 2 : 1,
  timeout: 60000,
  retries: process.env.CI ? 2 : 0,
  reporter: "html",
  use: {
    baseURL: e2eBaseUrl,
    trace: "on-first-retry",
  },
  webServer: {
    command: `node node_modules/next/dist/bin/next start --hostname 127.0.0.1 --port ${e2ePort}`,
    url: e2eBaseUrl,
    reuseExistingServer: false,
    timeout: 120000,
  },
  projects: [
    {
      name: "mobile",
      use: { ...devices["iPhone 13"], browserName: "chromium" },
    },
    {
      name: "webkit",
      use: { ...devices["iPhone 13"], browserName: "webkit" },
    },
    { name: "desktop", use: { ...devices["Desktop Chrome"] } },
  ],
});
