import type { MatchExercise } from "../../lib/media/types.ts";

type CatalogSeed = Omit<MatchExercise, "id">;
const row = (
  slug: string,
  namePt: string,
  nameEn: string,
  movementPattern: string,
  aliases: string[],
  equipment: string[],
  muscles: string[],
): CatalogSeed => ({
  slug,
  namePt,
  nameEn,
  movementPattern,
  aliases,
  equipment,
  muscles,
});
export const fallbackCatalog: CatalogSeed[] = [
  row(
    "leg-press",
    "Leg press",
    "Seated leg press",
    "squat",
    ["Leg press machine"],
    ["leg press", "machine"],
    ["quadriceps", "glute"],
  ),
  row(
    "hack-squat",
    "Hack squat",
    "Hack squat",
    "squat",
    ["Hack squat machine"],
    ["hack squat", "machine"],
    ["quadriceps", "glute"],
  ),
  row(
    "smith-squat",
    "Agachamento smith",
    "Smith machine squat",
    "squat",
    ["Smith squat"],
    ["smith machine", "barbell"],
    ["quadriceps", "glute"],
  ),
  row(
    "goblet-squat",
    "Goblet squat",
    "Goblet squat",
    "squat",
    ["Dumbbell goblet squat"],
    ["dumbbell"],
    ["quadriceps", "glute"],
  ),
  row(
    "leg-extension",
    "Cadeira extensora",
    "Leg extension",
    "knee_extension",
    ["Seated leg extension", "Leg extension machine"],
    ["leg extension", "machine"],
    ["quadriceps"],
  ),
  row(
    "lying-leg-curl",
    "Mesa flexora",
    "Lying leg curl",
    "knee_flexion",
    ["Prone leg curl"],
    ["leg curl", "machine"],
    ["hamstring"],
  ),
  row(
    "seated-leg-curl",
    "Cadeira flexora",
    "Seated leg curl",
    "knee_flexion",
    [],
    ["leg curl", "machine"],
    ["hamstring"],
  ),
  row(
    "hip-thrust",
    "Hip thrust",
    "Hip thrust",
    "hip_extension",
    ["Barbell hip thrust"],
    ["barbell", "bench"],
    ["glute"],
  ),
  row(
    "machine-glute",
    "Glúteo máquina",
    "Glute kickback machine",
    "hip_extension",
    ["Machine glute kickback"],
    ["glute machine"],
    ["glute"],
  ),
  row(
    "calf-raise",
    "Panturrilha",
    "Standing calf raise",
    "knee_extension",
    ["Calf raise"],
    ["bodyweight"],
    ["calf"],
  ),
  row(
    "lat-pulldown",
    "Puxada frontal",
    "Lat pulldown",
    "vertical_pull",
    ["Front pulldown"],
    ["lat pulldown", "cable"],
    ["latissimus", "back"],
  ),
  row(
    "neutral-pulldown",
    "Puxada neutra",
    "Neutral grip lat pulldown",
    "vertical_pull",
    [],
    ["lat pulldown", "cable"],
    ["latissimus", "back"],
  ),
  row(
    "supinated-pulldown",
    "Puxada supinada",
    "Reverse grip lat pulldown",
    "vertical_pull",
    ["Supinated pulldown"],
    ["lat pulldown", "cable"],
    ["latissimus", "biceps"],
  ),
  row(
    "seated-row",
    "Remada baixa",
    "Seated cable row",
    "horizontal_pull",
    ["Cable row", "Low row", "Seated row"],
    ["cable", "row machine"],
    ["back", "biceps"],
  ),
  row(
    "machine-row",
    "Remada articulada",
    "Seated row machine",
    "horizontal_pull",
    ["Row machine"],
    ["row machine"],
    ["back", "biceps"],
  ),
  row(
    "one-arm-row",
    "Remada unilateral",
    "One arm dumbbell row",
    "horizontal_pull",
    ["Single arm dumbbell row"],
    ["dumbbell", "bench"],
    ["back", "biceps"],
  ),
  row(
    "reverse-fly",
    "Reverse fly",
    "Reverse fly",
    "posture",
    ["Rear delt fly"],
    ["machine", "dumbbell"],
    ["rear deltoid", "trapezius"],
  ),
  row(
    "face-pull",
    "Face pull",
    "Cable face pull",
    "posture",
    ["Face pull"],
    ["cable", "rope"],
    ["rear deltoid", "trapezius"],
  ),
  row(
    "machine-chest-press",
    "Supino máquina",
    "Seated chest press",
    "horizontal_push",
    ["Chest press machine", "Chest press"],
    ["chest press", "machine"],
    ["chest", "triceps"],
  ),
  row(
    "incline-machine-press",
    "Supino inclinado máquina",
    "Incline chest press machine",
    "horizontal_push",
    ["Incline press"],
    ["chest press", "machine"],
    ["chest", "shoulder"],
  ),
  row(
    "machine-fly",
    "Crucifixo máquina",
    "Pec deck",
    "horizontal_push",
    ["Machine chest fly"],
    ["pec deck", "machine"],
    ["chest"],
  ),
  row(
    "machine-shoulder-press",
    "Desenvolvimento máquina",
    "Seated shoulder press machine",
    "vertical_push",
    ["Shoulder press machine"],
    ["shoulder press", "machine"],
    ["shoulder", "triceps"],
  ),
  row(
    "lateral-raise",
    "Elevação lateral",
    "Dumbbell lateral raise",
    "vertical_push",
    ["Lateral raise"],
    ["dumbbell"],
    ["deltoid", "shoulder"],
  ),
  row(
    "dead-bug",
    "Dead bug",
    "Dead bug exercise",
    "core_anti_extension",
    ["Dead bug"],
    ["bodyweight"],
    ["core", "abdominal"],
  ),
  row(
    "plank",
    "Prancha",
    "Forearm plank",
    "core_anti_extension",
    ["Plank exercise"],
    ["bodyweight"],
    ["core", "abdominal"],
  ),
  row(
    "pallof-press",
    "Pallof press",
    "Cable Pallof press",
    "core_anti_rotation",
    ["Pallof press"],
    ["cable"],
    ["core", "abdominal"],
  ),
  row(
    "farmer-walk",
    "Farmer walk",
    "Farmer carry",
    "carry",
    ["Farmers walk"],
    ["dumbbell", "kettlebell"],
    ["forearm", "core"],
  ),
  row(
    "wall-slide",
    "Wall slide",
    "Wall slide exercise",
    "posture",
    ["Wall angel"],
    ["bodyweight", "wall"],
    ["shoulder", "back"],
  ),
  row(
    "chin-tuck",
    "Chin tuck",
    "Chin tuck exercise",
    "posture",
    ["Cervical retraction"],
    ["bodyweight"],
    ["neck"],
  ),
  row(
    "thoracic-extension",
    "Extensão torácica",
    "Thoracic extension exercise",
    "mobility",
    ["Thoracic spine extension"],
    ["bench", "foam roller"],
    ["thoracic spine"],
  ),
  row(
    "treadmill",
    "Esteira",
    "Treadmill walking",
    "cardio",
    ["Walking on treadmill"],
    ["treadmill"],
    ["cardiovascular"],
  ),
  row(
    "incline-treadmill",
    "Esteira inclinada",
    "Incline treadmill walking",
    "cardio",
    ["Incline walking"],
    ["treadmill"],
    ["cardiovascular", "glute"],
  ),
  row(
    "bike",
    "Bicicleta",
    "Stationary bicycle",
    "cardio",
    ["Exercise bike"],
    ["stationary bike"],
    ["cardiovascular", "quadriceps"],
  ),
  row(
    "elliptical",
    "Elíptico",
    "Elliptical trainer",
    "cardio",
    ["Cross trainer"],
    ["elliptical"],
    ["cardiovascular"],
  ),
  row(
    "walking",
    "Caminhada",
    "Brisk walking",
    "cardio",
    ["Walking exercise"],
    ["bodyweight"],
    ["cardiovascular"],
  ),
];

export const seededPendingCandidateSlugs = new Set([
  "leg-press",
  "machine-chest-press",
  "machine-row",
]);
